import { StyleSheet } from "react-native";

const stylesData = StyleSheet.create({
  container: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-around",
    backgroundImage:
      "linear-gradient(325deg, rgba(47,141,155,1) 0%, rgba(47,141,155,1) 17%, rgba(47,141,155,1) 37%, rgba(47,141,155,1) 49%, rgba(55,154,170,1) 62%, rgba(55,154,170,1) 74%, rgba(57,160,176,1) 88%, rgba(67,181,198,1) 100%)",
  },
  containerLogo: {
    display: "flex",
    flex: 0.25,
    justifyContent: "center",
    alignItems: "center",
  },
  containerImg: {
    width: "40%",
    height: "80%",
    backgroundColor: "#DADADA",
    borderRadius: "50%",
    shadowColor: "#333",
    shadowOffset: {
      width: 3.2,
      height: 4.4,
    },
    shadowOpacity: 0.7,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 2.2,
    borderColor: "#333",
  },
  containerText: {
    display: "flex",
    flexDirection: "colum",
    justifyContent: "space-around",
    flex: 0.25,
    alignItems: "start",
    margin: "auto",
  },
  textCenter: {
    display: "flex",
    flexDirection: "colum",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 28,
    fontWeight: "bold",
    marginLeft: "7%",
  },
  subText: {
    display: "flex",
    flexDirection: "colum",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    textDecorationStyle: "solid",
    textDecorationLine: "underline",
    fontSize: 11,
    fontWeight: "500",
  },
  containerInfo: {
    width: "80%",
    maxHeight: "33vh",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-evenly",
    flex: 0.5,
    alignItems: "start",
    marginTop: 0,
    margin: "auto",
    backgroundColor: "white",
    borderBlockColor: "black",
    borderWidth: "3px",
    overflow: "scroll",
  },
  divInfos: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-evenly",
    fontSize: 18,
  },
  exibir: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    width: "80%",
    margin: "auto",
  },
  info: {
    display: "flex",
    width: "20%",
    alignItems: "center",
    backgroundColor: "white",
    borderColor: "none",
  },
  button: {
    display: "flex",
    flexDirection: "colum",
    position: "relative",
    backgroundColor: "#DADADA",
    borderRadius: 50,
    paddingVertical: 8,
    width: "60%",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#333",
    shadowOffset: {
      width: 2.2,
      height: 3.5,
    },
    shadowOpacity: 0.7,
    shadowRadius: 2.6,
    elevation: 5,
  },
});

export default stylesData;
