import { StyleSheet } from "react-native";

const stylesCard = StyleSheet.create({
  body: {
    overflow: "scroll",
    backgroundColor: "rgb(240,240,240)",
    paddingBottom: "15%",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    position: "absolute",
    top: "0",
    zIndex: "0",
    width: "100vw",
    height: "262px",
    backgroundColor: "rgba(42,128,142,1)",
  },

  container: {
    display: "flex",
    flexDirection: "colum",
    alignItems: "center",
    justifyContent: "space-around",
    flexWrap: "wrap",
    width: "95vw",
    margin: "auto",
    marginTop: "100px",
    zIndex: "499",
    gap: "50px",
  },
  cardStyle: {
    display: "flex",
    flexDirection: "column",
    width: "310px",
    height: "550px",
    marginBottom: "30px",
    margin: "auto",
    zIndex: "1",
    borderRadius: "14px",
  },
  cardImg: {
    width: "200px",
    height: "200px",
    borderRadius: "50%",
    margin: "auto",
    zIndex: "999",
    borderWidth: 2.2,
    borderColor: "#333",
    transition: "transform 0.3s ease",
    "&:hover": {
      transform: "scale(1.1)",
    },
  },
  card: {
    backgroundColor: "rgba(200,200,200,0.84)",
    paddingBottom: "10px",
    boxShadow: "7px 4px 4px rgba(20, 20, 20, 0.7)",
    borderRadius: "5%",
  },
  cardNome: {
    margin: "auto",
    alignItems: "center",
    justifyContent: "center",
    width: "50%",
    textAlign: "center",
  },
  cardIcon: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "85px",
    height: "50px",
    margin: "auto",
  },
  cardIconLeft: {
    position: "absolute",
    display: "flex",
    marginLeft: "0",
    left: "0",
    alignItems: "center",
    justifyContent: "center",
    width: "50px",
    height: "50px",
    zIndex: "999",
  },
  cardText: {
    display: "flex",
    top: "0",
    margin: "auto",
    alignItems: "flex-center",
    justifyContent: "flex-center",
    width: "50px",
    height: "50px",
    backgroundColor: "gray",
    zIndex: "999",
    fontFamily: "Helvetica",
  },
  cardIconRight: {
    position: "absolute",
    top: "0",
    right: "0",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    display: "flex",
    width: "50px",
    height: "50px",
    backgroundColor: "gray",
    zIndex: "999",
  },
  cardIconOne: {
    display: "flex",
    width: "40px",
    height: "40px",
  },
  cardIconTwo: {
    display: "flex",
    width: "40px",
    height: "40px",
  },
  cardText: {
    maxWidth: "280px",
    textAlign: "center",
    margin: "auto",
    fontWeight: "500",
    fontFamily: "helvetica",
  },
});

export default stylesCard;
